package com.example;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

@Controller    // This means that this class is a Controller
 // This means URL's start with /demo (after Application path)


public class MainController {
	@Autowired // This means to get the bean called LoanRequestRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private LoanRequestRepository loanRequestRepo;
	private ModelforUserData modelforUserData;
	
	@RequestMapping(value="/newpersonalloanrequest",method=RequestMethod.POST)
	String createform(@RequestParam("firstname") String firstName,
			@RequestParam("loanamount") String amount,
			@RequestParam("mobilenum") String mobileNum,Model model) {
		model.addAttribute("name",firstName);
		model.addAttribute("amount",amount);
		model.addAttribute("mobile",mobileNum);
		modelforUserData=new ModelforUserData(firstName, amount, mobileNum);
		NewLoanRequest newLoanReq=new NewLoanRequest();
		newLoanReq.setName(firstName);
		newLoanReq.setLoanRequired(Integer.parseInt(amount));
		newLoanReq.setMobileNumber(Integer.parseInt(mobileNum));
		loanRequestRepo.save(newLoanReq);
		return "WelcomeUser";
			
	}

}
